d cmake
fd cmake\CMakeLists-template-internal.cmake

; at_cmd
d component\at_cmd

; audio
f component\audio\Kconfig
f component\audio\CMakeLists.txt
f component\audio\audio_mixer.cmake
f component\audio\audio_passthrough.cmake
f component\audio\base.cmake
f component\audio\play_back.cmake

d component\audio\base\osal\osal_c\include
d component\audio\base\log\include
d component\audio\base\xlib\include
f component\audio\base\cutils\include\cutils\compat.h
f component\audio\base\cutils\include\cutils\compiler.h
f component\audio\base\cutils\include\cutils\container_of.h
f component\audio\base\cutils\include\cutils\uthash.h
f component\audio\base\cutils\include\cutils\utlist.h
f component\audio\base\cutils\include\cutils\ring_buffer.h

d component\audio\foundation\include

d component\audio\audio_cmds

d component\audio\audio_hal\a2dp
d component\audio\audio_hal\common
f component\audio\audio_hal\CMakeLists.txt

d component\audio\interfaces\audio
d component\audio\interfaces\hardware
d component\audio\interfaces\common
d component\audio\interfaces\media

d component\audio\audio_driver\include
f component\audio\audio_driver\CMakeLists.txt
f component\audio\audio_driver\audio_amplifier.c
f component\audio\audio_driver\amp_dummy.c
f component\audio\audio_driver\amp_dummy.h
f component\audio\audio_driver\ht513.c
f component\audio\audio_driver\ht513.h

f component\audio\third_party\CMakeLists.txt
d component\audio\third_party\flac
d component\audio\third_party\haac
d component\audio\third_party\libgsm
d component\audio\third_party\libopus
d component\audio\third_party\speexdsp
d component\audio\third_party\tremolo

d component\audio\examples\audio_hal_capture
d component\audio\examples\audio_hal_render

d component\audio\cmds


; ipc
f component\utils\CMakeLists.txt


; bluetooth
f component\bluetooth\CMakeLists.txt
f component\bluetooth\Kconfig


d component\bluetooth\bt_mp

d component\bluetooth\driver
fd component\bluetooth\driver\hci\hci_if_zephyr.c
fd component\bluetooth\driver\hci\hci_if_zephyr.h
dd component\bluetooth\driver\platform
dd component\bluetooth\driver\vhci

f component\bluetooth\example\CMakeLists.txt
d component\bluetooth\example\ble_central
d component\bluetooth\example\ble_mesh_device
d component\bluetooth\example\ble_mesh_device_scatternet
d component\bluetooth\example\ble_mesh_ota
dd component\bluetooth\example\ble_mesh_ota\platform
d component\bluetooth\example\ble_mesh_provisioner
d component\bluetooth\example\ble_mesh_provisioner_scatternet
d component\bluetooth\example\ble_peripheral
d component\bluetooth\example\ble_scatternet
d component\bluetooth\example\ble_throughput
d component\bluetooth\example\ble_wifimate
d component\bluetooth\example\gatt_service
fd component\bluetooth\example\gatt_service\server\rtk_hids.c
fd component\bluetooth\example\gatt_service\server\rtk_hids.h
fd component\bluetooth\example\gatt_service\server\rtk_hids_rmc.c
fd component\bluetooth\example\gatt_service\server\rtk_hids_rmc.h

d component\bluetooth\osif

d component\bluetooth\rtk_coex

f component\bluetooth\rtk_stack\CMakeLists.txt
d component\bluetooth\rtk_stack\inc
f component\bluetooth\rtk_stack\platform\CMakeLists.txt
d component\bluetooth\rtk_stack\platform\common
d component\bluetooth\rtk_stack\src\mesh


; example
; atcmd_host
d example\atcmd_host

; network_protocol
d example\network_protocol\bcast
d example\network_protocol\coap
d example\network_protocol\http_client
d example\network_protocol\http_download
d example\network_protocol\httpc
d example\network_protocol\httpd
d example\network_protocol\httpd_vfs
d example\network_protocol\ipv6
d example\network_protocol\lwip_mdns
d example\network_protocol\mcast
d example\network_protocol\mqtt
d example\network_protocol\nonblock_connect
d example\network_protocol\sntp_showtime
d example\network_protocol\socket_select
d example\network_protocol\socket_tcp_multithread
d example\network_protocol\tcp_keepalive
d example\network_protocol\websocket_client
d example\network_protocol\websocket_server

; ssl
d example\ssl\ssl_client
d example\ssl\ssl_client_mbedtls_dtls
d example\ssl\ssl_client_verify_both
d example\ssl\ssl_client_verify_required
d example\ssl\ssl_server
d example\ssl\ssl_server_mbedtls_dtls
d example\ssl\ssl_server_verify_both
d example\ssl\ssl_server_verify_required

; storage
d example\storage\vfs
d example\storage\kv
d example\storage\vfs_encrypt


; wifi
d example\wifi\wifi_enterprise
d example\wifi\wifi_csi
d example\wifi\wifi_event
d example\wifi\wifi_raw
d example\wifi\wifi_roaming
d example\wifi\wifi_roaming_plus
d example\wifi\wifi_user_reconnect
d example\wifi\wifi_tdma_scan
d example\wifi\wifi_diagnose_mqtt
d example\wificast

d example\cJSON
d example\ota
d example\xml
d example\mp_app_integration

; filesystem
f component\file_system\Kconfig
f component\file_system\CMakeLists.txt
d component\file_system\fatfs
d component\file_system\system_data

d component\file_system\kv
d component\file_system\vfs

; lwip
f component\lwip\Kconfig
f component\lwip\CMakeLists.txt
d component\lwip\lwip_v2.1.2
d component\lwip\api

; network
f component\network\CMakeLists.txt
d component\network\cJSON
d component\network\coap
d component\network\dhcp
d component\network\httpc
d component\network\httpd

f component\network\dnrd\src\CMakeLists.txt

d component\network\httplite
d component\network\iperf
d component\network\iperf3
d component\network\libcoap\include
d component\network\mqtt
d component\network\ping
d component\network\rtsp
d component\network\sntp
d component\network\websocket
d component\network\xml
d component\network\http2

; os
f component\os\Kconfig
f component\os\CMakeLists.txt
d component\os\os_wrapper
f component\os\freertos\CMakeLists.txt
d component\os\freertos\os_wrapper
d component\os\freertos\heap_trace

d component\os\freertos\freertos_posix



f component\os\freertos\freertos_service.c
f component\os\freertos\freertos_service.h
f component\os\freertos\freertos_backtrace_ext.c
f component\os\freertos\freertos_backtrace_ext.h
f component\os\freertos\freertos_heap5_config.c
f component\os\freertos\freertos_heap5_config.h


; ssl
d component\ssl

f component\wifi\CMakeLists.txt
f component\wifi\wifi_feature_disable\gen_noused_c.py
f component\wifi\api\CMakeLists.txt
f component\wifi\common\CMakeLists.txt
f component\wifi\driver\CMakeLists.txt
f component\wifi\wifi_feature_disable\CMakeLists.txt
f component\wifi\rtk_app\wifi_tunnel_app\CMakeLists.txt
f component\wifi\whc\CMakeLists.txt
f component\wifi\rtk_app\CMakeLists.txt
f component\wifi\wpa_supplicant\wpa_lite\CMakeLists.txt
f component\wifi\wpa_supplicant\src\wps\CMakeLists.txt
f component\wifi\wpa_supplicant\src\eap_peer\CMakeLists.txt
f component\wifi\wpa_supplicant\src\p2p\CMakeLists.txt
f component\wifi\Kconfig.wifi

; wifi api
d component\wifi\api
dd component\wifi\api\11s_path_selection
;d component\wifi\dpp

;wifi whc
d component\wifi\whc\whc_dev
dd component\wifi\whc\whc_dev\ipc
d component\wifi\whc\whc_host_rtos
dd component\wifi\whc\whc_host_rtos\ipc

;whc ipc
f component\wifi\whc\whc_def.h
f component\wifi\whc\whc_ipc.h
f component\wifi\whc\whc_ipc_cfg.h
f component\wifi\whc\whc_ipc_msg_queue.h
f component\wifi\whc\whc_dev\ipc\whc_ipc_dev_trx.h
f component\wifi\whc\whc_host_rtos\ipc\whc_ipc_host_trx.h
f component\wifi\whc\whc_host_rtos\ipc\whc_ipc_host_api.h

d component\wifi\promisc
d component\wifi\rtk_app\wifi_init
d component\wifi\rtk_app\wifi_fast_connect
d component\wifi\rtk_app\wifi_auto_reconnect
d component\wifi\rtk_app\wifi_feature_disable
d component\wifi\rtk_app\wifi_tunnel_app


;wifi simple config

;wifi_driver
f component\wifi\common\rtw_inic_common.h
f component\wifi\common\rtw_wifi_common.h
f component\wifi\common\rtw_timer.c
f component\wifi\common\rtw_timer.h
f component\wifi\common\rtw_skbuff.h
f component\wifi\common\rtw_misc.h
f component\wifi\common\rtw_queue.c
f component\wifi\common\rtw_queue.h
f component\wifi\common\rtw_atomic.c
f component\wifi\common\rtw_atomic.h
f component\wifi\common\rtw_wakelock.c
f component\wifi\common\rtw_wakelock.h
f component\wifi\common\rtw_event.c
f component\wifi\common\wifi_performance_monitor.h
f component\wifi\driver\intf\wifi_intf_drv_to_lwip.h
f component\wifi\driver\intf\wifi_intf_drv_to_bt.h
f component\wifi\driver\intf\wifi_intf_drv_to_upper.h
f component\wifi\driver\intf\wifi_intf_ram_to_rom.h
f component\wifi\driver\intf\wifi_intf_drv_to_app_internal.h
f component\wifi\driver\include\rtw_autoconf.h
f component\wifi\driver\include\autoconf_debug.h
f component\wifi\driver\include\autoconf_eap.h
f component\wifi\driver\include\rtw_byteorder.h
f component\wifi\common\secure\rom_secure_common.h
f component\wifi\driver\halcommon_rom\rom_hal_rom_to_flash.h

;rtk_coex
f component\rtk_coex\rtw_coex_ipc_host.c
f component\rtk_coex\rtw_coex_host_api_com.c
f component\rtk_coex\rtw_coex_host_api_bt.c
f component\rtk_coex\rtw_coex_host_api_ext.c
f component\rtk_coex\rtw_coex_host_api_wp.c
f component\rtk_coex\rtw_coex_ipc_host_api.c
f component\rtk_coex\rtw_coex_ipc_def.h
f component\rtk_coex\rtw_coex_ipc_cfg.h
f component\rtk_coex\rtw_coex_host_api.h
f component\rtk_coex\rtw_coex_ipc.h
f component\rtk_coex\rtw_coex_api_ext.h
f component\rtk_coex\CMakeLists.txt
f component\rtk_coex\rtk_coex_api.cmake
f component\rtk_coex\rtk_coex.cmake
f component\rtk_coex\Kconfig.coex

; pqc
d component\soc\common\pqc

;wpa_supplicant
f component\wifi\wpa_supplicant\src\common\defs.h
f component\wifi\wpa_supplicant\src\common\ieee802_11_common.c
f component\wifi\wpa_supplicant\src\common\ieee802_11_common.h
f component\wifi\wpa_supplicant\src\common\ieee802_11_defs.h
f component\wifi\wpa_supplicant\src\crypto\crypto.h
f component\wifi\wpa_supplicant\src\crypto\des_i.h
f component\wifi\wpa_supplicant\src\crypto\des-internal.c
f component\wifi\wpa_supplicant\src\crypto\md4-internal.c
f component\wifi\wpa_supplicant\src\crypto\ms_funcs.c
f component\wifi\wpa_supplicant\src\crypto\ms_funcs.h
f component\wifi\wpa_supplicant\src\crypto\random.c
f component\wifi\wpa_supplicant\src\crypto\random.h
f component\wifi\wpa_supplicant\src\crypto\rc4.c
f component\wifi\wpa_supplicant\src\crypto\sha1.h
f component\wifi\wpa_supplicant\src\crypto\sha1_i.h
f component\wifi\wpa_supplicant\src\crypto\sha1-internal.c
f component\wifi\wpa_supplicant\src\crypto\sha256.h
f component\wifi\wpa_supplicant\src\crypto\tls_polarssl.c
f component\wifi\wpa_supplicant\src\crypto\tls.h
f component\wifi\wpa_supplicant\src\eap_common\eap_common.c
f component\wifi\wpa_supplicant\src\eap_common\eap_common.h
f component\wifi\wpa_supplicant\src\eap_common\eap_defs.h
f component\wifi\wpa_supplicant\src\eap_common\eap_peap_common.c
f component\wifi\wpa_supplicant\src\eap_common\eap_peap_common.h
f component\wifi\wpa_supplicant\src\eap_common\eap_tlv_common.h
f component\wifi\wpa_supplicant\src\eap_common\eap_ttls.h
f component\wifi\wpa_supplicant\src\eap_common\eap_wsc_common.c
f component\wifi\wpa_supplicant\src\eap_common\eap_wsc_common.h
f component\wifi\wpa_supplicant\src\eap_peer\eap.c
f component\wifi\wpa_supplicant\src\eap_peer\eap.h
f component\wifi\wpa_supplicant\src\eap_peer\eap_config.h
f component\wifi\wpa_supplicant\src\eap_peer\eap_i.h
f component\wifi\wpa_supplicant\src\eap_peer\eap_methods.c
f component\wifi\wpa_supplicant\src\eap_peer\eap_methods.h
f component\wifi\wpa_supplicant\src\eap_peer\eap_mschapv2.c
f component\wifi\wpa_supplicant\src\eap_peer\eap_peap.c
f component\wifi\wpa_supplicant\src\eap_peer\eap_tls.c
f component\wifi\wpa_supplicant\src\eap_peer\eap_tls_common.c
f component\wifi\wpa_supplicant\src\eap_peer\eap_tls_common.h
f component\wifi\wpa_supplicant\src\eap_peer\eap_ttls.c
f component\wifi\wpa_supplicant\src\eap_peer\eap_wsc.c
f component\wifi\wpa_supplicant\src\eap_peer\eap_wsc.h
f component\wifi\wpa_supplicant\src\eap_peer\mschapv2.c
f component\wifi\wpa_supplicant\src\eap_peer\mschapv2.h
f component\wifi\wpa_supplicant\src\eap_server\eap_server_wsc.c
f component\wifi\wpa_supplicant\src\eap_server\eap_server_wsc.h
f component\wifi\wpa_supplicant\src\p2p\p2p.h
f component\wifi\wpa_supplicant\src\p2p\p2p_i.h
f component\wifi\wpa_supplicant\src\utils\common.c
f component\wifi\wpa_supplicant\src\utils\common.h
f component\wifi\wpa_supplicant\src\utils\includes.h
f component\wifi\wpa_supplicant\src\utils\os.h
f component\wifi\wpa_supplicant\src\utils\state_machine.h
f component\wifi\wpa_supplicant\src\utils\uuid.h
f component\wifi\wpa_supplicant\src\utils\wpa_debug.h
f component\wifi\wpa_supplicant\src\utils\wpabuf.h
f component\wifi\wpa_supplicant\src\utils\rom\rom_wps_os.h
f component\wifi\wpa_supplicant\src\wps\wps_defs.h
f component\wifi\wpa_supplicant\src\wps\wps_i.h
f component\wifi\wpa_supplicant\src\wps\wps.h
f component\wifi\wpa_supplicant\src\wps\wps_attr_parse.h
f component\wifi\wpa_supplicant\wpa_supplicant\eap_protocol_handler.c
f component\wifi\wpa_supplicant\wpa_supplicant\eap_protocol_handler.h
f component\wifi\wpa_supplicant\wpa_supplicant\wifi_eap_config.c
f component\wifi\wpa_supplicant\wpa_supplicant\wifi_wps_config.c
f component\wifi\wpa_supplicant\wpa_supplicant\wifi_wps_config.h
f component\wifi\wpa_supplicant\wpa_supplicant\wifi_p2p_config.c
f component\wifi\wpa_supplicant\wpa_supplicant\wifi_p2p_config.h
f component\wifi\wpa_supplicant\wpa_supplicant\wifi_p2p_disable.c
f component\wifi\wpa_supplicant\wpa_supplicant\wifi_p2p_supplicant.h
f component\wifi\wpa_supplicant\wpa_supplicant\wps_protocol_handler.h
f component\wifi\wpa_supplicant\wpa_lite\wpa_lite.h
f component\wifi\wpa_supplicant\wpa_lite\wpa_lite_intf.h
f component\wifi\wpa_supplicant\wpa_lite\wpa_lite_psk.h
f component\wifi\wpa_supplicant\wpa_lite\rom\rom_wpa_lite_intf.h
f component\wifi\wpa_supplicant\wpa_lite\rom\rom_wpa_lite_psk.h

f component\wifi\wifi_fw\CMakeLists.txt
f component\wifi\wifi_fw\common\wififw_common.cmake

f example\CMakeLists.txt
dd example\peripheral\raw\CapTouch\raw_ctc_sw_filter
dd example\peripheral\raw\GDMA\gather_scatter


; ui
f component\ui\Kconfig
f component\ui\CMakeLists.txt
d component\ui\drivers
d component\ui\LVGL
d component\ui\third_party\libjpeg-turbo
d component\ui\third_party\libpng
d component\ui\third_party\zlib
f component\ui\third_party\CMakeLists.txt
f component\ui\third_party\Kconfig
dd component\ui\LVGL\lvgl-8.3\lvgl
dd component\ui\LVGL\lvgl-9.3\lvgl
d component\ui\examples

; doc
f doc\AN0025*.*


; tools
; ameba
d tools\ameba\AudioTestTool
d tools\ameba\CapTestTool
d tools\ameba\DeviceProfileEditor
fd tools\ameba\DeviceProfileEditor\AmebaDeviceProfileEditor(Internal).exe
d tools\ameba\DeviceProfileEditor_Legacy
fd tools\ameba\DeviceProfileEditor_Legacy\AmebaDeviceProfileEditor(Internal).exe
d tools\ameba\ImageTool
d tools\ameba\Flash
fd tools\ameba\Flash\.gitignore
d tools\ameba\Monitor
d tools\ameba\ImageTool_Legacy
d tools\ameba\MP_ImageTool_1_N_Legacy
d tools\ameba\MP_ImageTool_1_N_Linux_Legacy
d tools\ameba\TraceTool
d tools\ameba\R-DIAG_Demo_Tool
fd tools\ameba\TraceTool\AmebaTraceTool(Internal).exe
f tools\ameba\RemoteService\remote_serial.py
f tools\ameba\RemoteService\version_manager.py

d tools\littlefs
d tools\DownloadServer
d tools\DownloadServer(HTTP)
d tools\DownloadServer(UART)
d tools\image_scripts
dd tools\image_scripts\internal

d tools\R-Mesh_Demo_Tool
f tools\requirements.txt
d tools\scripts
dd tools\scripts\git_hooks
fd tools\scripts\.gitignore
fd tools\scripts\setup.py
fd tools\scripts\update.py
fd tools\scripts\rtk_utils.py
fd tools\scripts\socmap_generate.py
dd tools\scripts\__pycache__
dd tools\scripts\image_process\__pycache__
dd tools\scripts\release_tool
fd tools\scripts\jlink_script\SWDPWD_Verify.JLinkScript
dd tools\scripts\img_utility

f \env.bat
f \env.sh
f \ameba.py
f \Realtek_Disclaimer-2019.pdf
f \LICENSE
f \README.md
f \.gitignore
