; cmake
fd component\at_cmd\atcmd_wpan.c
d component\audio\libs\amebadplus
d component\audio\audio_hal\amebadplus
d component\audio\configs\
d component\audio\examples\audio_manager
dd component\audio\examples\voice
; aivoice
d component\aivoice
dd component\aivoice\examples
dd component\aivoice\.git
d component\aivoice\examples\build_utils
d component\aivoice\examples\full_flow_offline
;d component\utils\ipc\ipc\
d component\utils\ringbuffer
; crashdump
d component\soc\common\rtk_assert
d component\soc\common\crashdump\
dd component\soc\common\crashdump\arm
dd component\soc\common\crashdump\riscv
fd component\soc\common\crashdump\ameba_freertos_backtrace.c
fd component\soc\common\crashdump\include\ameba_rv32_backtrace.h
fd component\soc\common\crashdump\include\ameba_rv32_crashdump.h
f component\bluetooth\Kconfig.inic
f component\bluetooth\api\include\bt_api_config.h
f component\bluetooth\api\include\bt_app_config.h
f component\bluetooth\api\include\bt_vendor_config.h
f component\bluetooth\api\include\rtk_bt_att_defs.h
f component\bluetooth\api\include\rtk_bt_common.h
f component\bluetooth\api\include\rtk_bt_def.h
f component\bluetooth\api\include\rtk_bt_device.h
f component\bluetooth\api\include\rtk_bt_gap.h
f component\bluetooth\api\include\rtk_bt_gattc.h
f component\bluetooth\api\include\rtk_bt_gatts.h
f component\bluetooth\api\include\rtk_bt_le_gap.h
f component\bluetooth\api\include\rtk_bt_mesh_common.h
f component\bluetooth\api\include\rtk_bt_mesh_config_client_model.h
f component\bluetooth\api\include\rtk_bt_mesh_datatrans_model.h
f component\bluetooth\api\include\rtk_bt_mesh_def.h
f component\bluetooth\api\include\rtk_bt_mesh_device_firmware_update_model.h
f component\bluetooth\api\include\rtk_bt_mesh_directed_forwarding_model.h
f component\bluetooth\api\include\rtk_bt_mesh_generic_default_transition_time.h
f component\bluetooth\api\include\rtk_bt_mesh_generic_model.h
f component\bluetooth\api\include\rtk_bt_mesh_generic_onoff_model.h
f component\bluetooth\api\include\rtk_bt_mesh_health_model.h
f component\bluetooth\api\include\rtk_bt_mesh_light_model.h
f component\bluetooth\api\include\rtk_bt_mesh_performence_test.h
f component\bluetooth\api\include\rtk_bt_mesh_private_beacon_model.h
f component\bluetooth\api\include\rtk_bt_mesh_remote_prov_model.h
f component\bluetooth\api\include\rtk_bt_mesh_scene_model.h
f component\bluetooth\api\include\rtk_bt_mesh_scheduler_model.h
f component\bluetooth\api\include\rtk_bt_mesh_sensor_model.h
f component\bluetooth\api\include\rtk_bt_mesh_subnet_bridge_model.h
f component\bluetooth\api\include\rtk_bt_mesh_time_model.h
f component\bluetooth\api\include\rtk_bt_power_control.h
f component\bluetooth\api\include\rtk_bt_vendor.h
f component\bluetooth\api\rtk_stack\CMakeLists.txt
f component\bluetooth\api\rtk_stack\rtk_stack_api.c
f component\bluetooth\api\rtk_stack\rtk_stack_config.h
f component\bluetooth\api\rtk_stack\rtk_stack_gap.c
f component\bluetooth\api\rtk_stack\rtk_stack_gatt.h
f component\bluetooth\api\rtk_stack\rtk_stack_gattc.c
f component\bluetooth\api\rtk_stack\rtk_stack_gatts.c
f component\bluetooth\api\rtk_stack\rtk_stack_internal.h
f component\bluetooth\api\rtk_stack\rtk_stack_le_gap.c
f component\bluetooth\api\rtk_stack\rtk_stack_mesh_common.c
f component\bluetooth\api\rtk_stack\rtk_stack_mesh_config_client_model.c
f component\bluetooth\api\rtk_stack\rtk_stack_mesh_datatrans_model.c
f component\bluetooth\api\rtk_stack\rtk_stack_mesh_device_firmware_update_model.c
f component\bluetooth\api\rtk_stack\rtk_stack_mesh_directed_forwarding_model.c
f component\bluetooth\api\rtk_stack\rtk_stack_mesh_generic_default_transition_time.c
f component\bluetooth\api\rtk_stack\rtk_stack_mesh_generic_model.c
f component\bluetooth\api\rtk_stack\rtk_stack_mesh_generic_onoff_model.c
f component\bluetooth\api\rtk_stack\rtk_stack_mesh_health_model.c
f component\bluetooth\api\rtk_stack\rtk_stack_mesh_internal.h
f component\bluetooth\api\rtk_stack\rtk_stack_mesh_light_model.c
f component\bluetooth\api\rtk_stack\rtk_stack_mesh_private_beacon_model.c
f component\bluetooth\api\rtk_stack\rtk_stack_mesh_remote_prov_model.c
f component\bluetooth\api\rtk_stack\rtk_stack_mesh_scene_model.c
f component\bluetooth\api\rtk_stack\rtk_stack_mesh_scheduler_model.c
f component\bluetooth\api\rtk_stack\rtk_stack_mesh_sensor_model.c
f component\bluetooth\api\rtk_stack\rtk_stack_mesh_subnet_bridge_model.c
f component\bluetooth\api\rtk_stack\rtk_stack_mesh_time_model.c
f component\bluetooth\api\rtk_stack\rtk_stack_vendor.c
f component\bluetooth\api\rtk_stack\rtk_stack_vendor.h
f component\bluetooth\api\rtk_bt_common.c
f component\bluetooth\api\rtk_bt_device.c
f component\bluetooth\api\rtk_bt_gap.c
f component\bluetooth\api\rtk_bt_gatt.c
f component\bluetooth\api\rtk_bt_le_gap.c
f component\bluetooth\api\rtk_bt_mesh_common.c
f component\bluetooth\api\rtk_bt_mesh_config_client_model.c
f component\bluetooth\api\rtk_bt_mesh_datatrans_model.c
f component\bluetooth\api\rtk_bt_mesh_device_firmware_update_model.c
f component\bluetooth\api\rtk_bt_mesh_directed_forwarding_model.c
f component\bluetooth\api\rtk_bt_mesh_generic_default_transition_time.c
f component\bluetooth\api\rtk_bt_mesh_generic_model.c
f component\bluetooth\api\rtk_bt_mesh_generic_onoff_model.c
f component\bluetooth\api\rtk_bt_mesh_health_model.c
f component\bluetooth\api\rtk_bt_mesh_light_model.c
f component\bluetooth\api\rtk_bt_mesh_private_beacon_model.c
f component\bluetooth\api\rtk_bt_mesh_remote_prov_model.c
f component\bluetooth\api\rtk_bt_mesh_scene_model.c
f component\bluetooth\api\rtk_bt_mesh_scheduler_model.c
f component\bluetooth\api\rtk_bt_mesh_sensor_model.c
f component\bluetooth\api\rtk_bt_mesh_subnet_bridge_model.c
f component\bluetooth\api\rtk_bt_mesh_time_model.c
f component\bluetooth\api\rtk_bt_power_control.c
f component\bluetooth\api\rtk_bt_vendor.c
f component\bluetooth\api\CMakeLists.txt
dd component\bluetooth\bt_mp\bt_eqc
dd component\bluetooth\driver\bt_inic
f component\bluetooth\driver\bt_inic\bt_inic.h
f component\bluetooth\driver\bt_inic\bt_inic_defs.h
f component\bluetooth\driver\bt_inic\bt_inic_sdio_dplus.c
d component\bluetooth\driver\platform\amebadplus
d component\bluetooth\example\ble_mesh_ota\platform\amebadplus
d component\bluetooth\example\ble_transfer_module
f component\bluetooth\example\bt_atcmd\CMakeLists.txt
f component\bluetooth\example\bt_atcmd\atcmd_bt_cmd_sync.c
f component\bluetooth\example\bt_atcmd\atcmd_bt_cmd_sync.h
f component\bluetooth\example\bt_atcmd\atcmd_bt_common.c
f component\bluetooth\example\bt_atcmd\atcmd_bt_example.c
f component\bluetooth\example\bt_atcmd\atcmd_bt_gap.c
f component\bluetooth\example\bt_atcmd\atcmd_bt_gattc.c
f component\bluetooth\example\bt_atcmd\atcmd_bt_gatts.c
f component\bluetooth\example\bt_atcmd\atcmd_bt_impl.h
f component\bluetooth\example\bt_atcmd\atcmd_bt_le_gap.c
f component\bluetooth\example\bt_atcmd\atcmd_bt_mesh_common.c
f component\bluetooth\example\bt_atcmd\atcmd_bt_mesh_config_model.c
f component\bluetooth\example\bt_atcmd\atcmd_bt_mesh_datatrans_model.c
f component\bluetooth\example\bt_atcmd\atcmd_bt_mesh_device_firmware_update_model.c
f component\bluetooth\example\bt_atcmd\atcmd_bt_mesh_directed_forwarding.c
f component\bluetooth\example\bt_atcmd\atcmd_bt_mesh_generic_default_transition_time.c
f component\bluetooth\example\bt_atcmd\atcmd_bt_mesh_generic_model.c
f component\bluetooth\example\bt_atcmd\atcmd_bt_mesh_goo_model.c
f component\bluetooth\example\bt_atcmd\atcmd_bt_mesh_health_model.c
f component\bluetooth\example\bt_atcmd\atcmd_bt_mesh_light_model.c
f component\bluetooth\example\bt_atcmd\atcmd_bt_mesh_private_beacon_model.c
f component\bluetooth\example\bt_atcmd\atcmd_bt_mesh_remote_prov_model.c
f component\bluetooth\example\bt_atcmd\atcmd_bt_mesh_scene_model.c
f component\bluetooth\example\bt_atcmd\atcmd_bt_mesh_scheduler_model.c
f component\bluetooth\example\bt_atcmd\atcmd_bt_mesh_sensor_model.c
f component\bluetooth\example\bt_atcmd\atcmd_bt_mesh_subnet_bridge_model.c
f component\bluetooth\example\bt_atcmd\atcmd_bt_mesh_time_model.c
f component\bluetooth\example\bt_atcmd\atcmd_bt_throughput_test.c
f component\bluetooth\example\bt_atcmd\atcmd_bt_transfer_module.c
f component\bluetooth\example\bt_atcmd\atcmd_bt_vendor.c
f component\bluetooth\example\bt_atcmd\atcmd_bt_wifimate_configurator.c
f component\bluetooth\example\bt_atcmd\bt_utils.c
f component\bluetooth\example\bt_atcmd\bt_utils.h
dd component\bluetooth\rtk_stack\inc\ble_mgr
dd component\bluetooth\rtk_stack\inc\framework
dd component\bluetooth\rtk_stack\inc\bluetooth\leaudio
d component\bluetooth\rtk_stack\platform\amebadplus
dd component\bluetooth\rtk_stack\src\mesh\inc\amebasmart
dd component\bluetooth\rtk_stack\src\mesh\inc\amebalite
dd component\bluetooth\rtk_stack\src\mesh\inc\amebagreen2
dd component\bluetooth\rtk_stack\src\mesh\lib\amebasmart
dd component\bluetooth\rtk_stack\src\mesh\lib\amebalite
dd component\bluetooth\rtk_stack\src\mesh\lib\amebagreen2
; tflite_micro
d component\tflite_micro
dd component\tflite_micro\examples
dd component\tflite_micro\tflm_unittest
dd component\tflite_micro\.git
fd component\tflite_micro\.clang-format
fd component\tflite_micro\sync\extract_tflm_unittest_srcs.sh
d component\tflite_micro\examples\build_utils
d component\tflite_micro\examples\tflm_hello_world
d component\tflite_micro\examples\tflm_micro_speech
d component\tflite_micro\examples\tflm_mnist
fd component\tflite_micro\examples\tflm_mnist\run_internal.sh
d example\network_protocol\captive_portal
d example\storage\vfs_sd_spi
d example\storage\vfs_second_flash
; usb
d example\usb\usbd_cdc_acm
d example\usb\usbd_composite_cdc_acm_hid
d example\usb\usbd_composite_cdc_acm_uac
d example\usb\usbd_composite_cdc_acm_msc
d example\usb\usbd_composite_hid_uac
d example\usb\usbd_hid
d example\usb\usbd_msc
d example\usb\usbd_inic_dplus
d example\usb\usbd_uac
d example\usb\usbd_vendor
d example\wifi\wifi_nat_repeater
d example\wifi\wifi_rpp
f component\file_system\ftl\ftl.c
f component\file_system\ftl\ftl.h
f component\file_system\ftl\CMakeLists.txt
f component\file_system\littlefs\CMakeLists.txt
f component\file_system\littlefs\littlefs_adapter.c
f component\file_system\littlefs\littlefs_adapter.h
d component\file_system\littlefs\r2.50
d component\lwip\lwip_v2.1.2\src\core\ipv4\ip_nat
; fd component\lwip\lwip_v2.1.2\src\core\ipv4\ip_nat\lwip_ip4nat.c
d component\network\ssl_client
d component\os\freertos\freertos_v10.4.3
dd component\os\freertos\freertos_v10.4.3\portable\GCC
d component\os\freertos\freertos_v10.4.3\portable\GCC\AmebaDplus_KM0
d component\os\freertos\freertos_v10.4.3\portable\GCC\AmebaDplus_KM4
dd component\os\freertos\freertos_v10.4.3\portable\IAR
dd component\os\freertos\freertos_v10.4.3\portable\Keil
dd component\os\freertos\freertos_v10.4.3\portable\MemMang
f component\os\freertos\freertos_v10.4.3\portable\GCC\MemMang\heap5.c
; wifi makefile
;whc
d component\wifi\whc\whc_host_linux
d component\wifi\whc\whc_host_stm32
d component\wifi\whc\whc_host_threadx_fullhan
d component\wifi\whc\whc_host_zephyr
d component\wifi\whc\whc_host_rtos
dd component\wifi\whc\whc_host_rtos\ipc

;f component\wifi\simple_config\wifi_simple_config.c
;f component\wifi\simple_config\wifi_simple_config.h
;f component\wifi\simple_config\wifi_simple_config_parser.h
f component\wifi\driver\include\autoconf_8721da.h
f component\wifi\wifi_fw\amebadplus\CMakeLists.txt
;example
d example\peripheral\
dd example\peripheral\raw\CA32Trustzone
dd example\peripheral\raw\Display\MIPI
dd example\peripheral\raw\Thermal
dd example\peripheral\raw\ADC\raw_adc_comp_assist
dd example\peripheral\raw\ADC\raw_adc_sw_trig
dd example\peripheral\raw\ADC\raw_adc_tim_trig_vbat
dd example\peripheral\raw\GPIO\audio_pad
dd example\peripheral\raw\SDH
dd example\peripheral\raw\Flash\Flash_OTP
dd example\peripheral\raw\ECDSA
; usb class
d component\usb
dd component\usb\verification
d component\usb\common
fd component\usb\common\usb_hal.c
fd component\usb\common\usb_os.c
fd component\usb\common\usb_phy.c
fd component\usb\common\usb_ringbuf.c
fd component\usb\common\usb_hal.h
fd component\usb\common\usb_regs.h
dd component\usb\device\core
f component\usb\device\core\usbd.h
dd component\usb\device\inic
dd component\usb\device\verify
dd component\usb\host
dd component\ui\LVGL\lvgl-8.3\lv_drivers\amebasmart
dd component\ui\LVGL\lvgl-8.3\lv_drivers\amebalite
dd component\ui\LVGL\lvgl-8.3\lv_drivers\amebagreen2
dd component\ui\LVGL\lvgl-8.3\port\amebasmart
dd component\ui\LVGL\lvgl-8.3\port\amebalite
dd component\ui\LVGL\lvgl-8.3\port\amebagreen2
dd component\ui\LVGL\lvgl-9.3\lv_drivers\amebasmart
dd component\ui\LVGL\lvgl-9.3\lv_drivers\amebalite
dd component\ui\LVGL\lvgl-9.3\lv_drivers\amebagreen2
dd component\ui\LVGL\lvgl-9.3\port\amebasmart
dd component\ui\LVGL\lvgl-9.3\port\amebalite
dd component\ui\LVGL\lvgl-9.3\port\amebagreen2
fd tools\ameba\TraceTool\eFuseDefaultMap.json
d tools\iperf
f component\soc\amebadplus\project\AmebaDplus_Release_Note.txt
;
; file use f , dir use d
; "file copy and rename" use fr
; "file delete" use fd

; soc
d component\soc\amebadplus

dd component\soc\amebadplus\verification
dd component\soc\amebadplus\rom
dd component\soc\amebadplus\imgtool_floader

dd component\soc\amebadplus\lib
f component\soc\amebadplus\lib\bootloader\CMakeLists.txt
f component\soc\amebadplus\lib\chipinfo\CMakeLists.txt
f component\soc\amebadplus\lib\pmc\CMakeLists.txt

dd component\soc\amebadplus\app\hal

; tfm is not release temporary, because code size is too large for gitee.
; d component\soc\common\trusted-firmware-m
d component\soc\common\include
d component\soc\common\lzma
d component\soc\common\diagnose
d component\soc\common\cmsis-dsp
dd component\soc\common\cmsis-dsp\rom

d component\soc\usrcfg\amebadplus
d component\soc\usrcfg\common

; GCC version
; project files
f component\soc\amebadplus\project\CMakeLists.txt
f component\soc\amebadplus\project\postbuild.cmake
f component\soc\amebadplus\project\ameba_layout.ld
f component\soc\amebadplus\project\manifest.json5
f component\soc\amebadplus\project\Kconfig
f component\soc\amebadplus\project\default.conf

; km4
d component\soc\amebadplus\project\project_km4

; asdk
fd component\soc\amebadplus\project\project_km4\gnu_utility\platform_config.sh
dd component\soc\amebadplus\project\project_km4\gnu_utility\jtag_cfg
dd component\soc\amebadplus\project\project_km4\make_rom

fd component\soc\amebadplus\project\project_km4\libs.cmake
fd component\soc\amebadplus\project\project_km4\includeflags.cmake
fd component\soc\amebadplus\project\project_km4\bluetooth_include.cmake

dd component\soc\amebadplus\project\project_km4\lib
d component\soc\amebadplus\project\project_km4\lib\application
d component\soc\amebadplus\project\project_km4\lib\soc
dd component\soc\amebadplus\project\project_km4\make_lib
dd component\soc\amebadplus\project\project_km4\make_secure

fd component\soc\amebadplus\project\project_km4\ld\ameba_rom.ld
fd component\soc\amebadplus\project\project_km4\ld\ameba_rom_bin.ld
dd component\soc\amebadplus\project\project_km4\ld_ns

dd component\soc\amebadplus\project\project_km4\make
d component\soc\amebadplus\project\project_km4\make\image1
d component\soc\amebadplus\project\project_km4\make\image2
d component\soc\amebadplus\project\project_km4\make\image3
d component\soc\amebadplus\project\project_km4\make\image_floader
d component\soc\amebadplus\project\project_km4\make\image_imgtool_floader


; km0
d component\soc\amebadplus\project\project_km0

; asdk

fd component\soc\amebadplus\project\project_km0\libs.cmake
fd component\soc\amebadplus\project\project_km0\includeflags.cmake
fd component\soc\amebadplus\project\project_km0\bluetooth_include.cmake

dd component\soc\amebadplus\project\project_km0\make_rom

dd component\soc\amebadplus\project\project_km0\lib
d component\soc\amebadplus\project\project_km0\lib\application
d component\soc\amebadplus\project\project_km0\lib\soc
dd component\soc\amebadplus\project\project_km0\make_lib

fd component\soc\amebadplus\project\project_km0\ld\ameba_rom.ld
fd component\soc\amebadplus\project\project_km0\ld\ameba_rom_bin.ld

dd component\soc\amebadplus\project\project_km0\make
d component\soc\amebadplus\project\project_km0\make\image2
