# This file is generated automatically by : python menuconfig.py -s utils/confs_release_tool/rls_km4_audio.conf
CONFIG_AUDIO_FWK_MENU=y
CONFIG_USB_OTG_EN_MENU=y
CONFIG_USB_HOST_EN_MENU=y
CONFIG_USBH_COMPOSITE_MENU=y
CONFIG_USBH_COMPOSITE_HID_UAC_MENU=y
CONFIG_USBH_COMPOSITE_HID_UAC1_MENU=y
CONFIG_USBH_UAC_MENU=y
CONFIG_AUDIO_DEVICE_A2DP_MENU=y
CONFIG_AUDIO_DEVICE_USB_MENU=y
