;cmake
d component\audio\libs\amebalite
f component\audio\foundation\CMakeLists.txt
d component\audio\audio_hal\amebalite
d component\audio\configs\
d component\audio\examples\audio_manager
d component\audio\examples\speexdsp
d component\utils\ipc\
; ringbuffer
d component\utils\ringbuffer\
dd component\ui\LVGL\lvgl-8.3\lv_drivers\amebadplus
dd component\ui\LVGL\lvgl-8.3\lv_drivers\amebasmart
dd component\ui\LVGL\lvgl-8.3\lv_drivers\amebagreen2
dd component\ui\LVGL\lvgl-8.3\port\amebadplus
dd component\ui\LVGL\lvgl-8.3\port\amebasmart
dd component\ui\LVGL\lvgl-8.3\port\amebagreen2
dd component\ui\LVGL\lvgl-9.3\lv_drivers\amebadplus
dd component\ui\LVGL\lvgl-9.3\lv_drivers\amebasmart
dd component\ui\LVGL\lvgl-9.3\lv_drivers\amebagreen2
dd component\ui\LVGL\lvgl-9.3\port\amebadplus
dd component\ui\LVGL\lvgl-9.3\port\amebasmart
dd component\ui\LVGL\lvgl-9.3\port\amebagreen2
; crashdump
d component\soc\common\rtk_assert
d component\soc\common\crashdump\
dd component\soc\common\crashdump\arm
dd component\soc\common\crashdump\riscv
fd component\soc\common\crashdump\ameba_freertos_backtrace.c
d component\bluetooth\api
dd component\bluetooth\api\zephyr_stack
d component\bluetooth\bt_audio
fd component\bluetooth\bt_audio\audio_sync\bt_audio_sync.c
dd component\bluetooth\bt_audio\bt_codec\aac
d component\bluetooth\bt_audio\bt_codec\aac\libAACdec\include
d component\bluetooth\bt_audio\bt_codec\aac\libAACenc\include
dd component\bluetooth\bt_audio\bt_codec\lc3
d component\bluetooth\bt_audio\bt_codec\lc3\include
dd component\bluetooth\bt_audio\bt_codec\sbc
d component\bluetooth\bt_audio\bt_codec\sbc\common
d component\bluetooth\bt_audio\bt_codec\sbc\decoder\include
d component\bluetooth\bt_audio\bt_codec\sbc\encoder\include
d component\bluetooth\bt_audio\bt_codec\sbc\plc
fd component\bluetooth\bt_audio\bt_codec\sbc\plc\sbc_plc.c
dd component\bluetooth\bt_mp\bt_eqc
dd component\bluetooth\bt_mp\bt_fast_mp
dd component\bluetooth\driver\bt_inic
f component\bluetooth\driver\bt_inic\bt_inic.h
f component\bluetooth\driver\bt_inic\bt_inic_defs.h
fd component\bluetooth\driver\hci\hci_if_inic.c
fd component\bluetooth\driver\hci\hci_if_inic.h
d component\bluetooth\driver\platform\amebalite
d component\bluetooth\example\ble_mesh_ota\platform\amebalite
d component\bluetooth\example\bt_a2dp
d component\bluetooth\example\bt_a2dp_hfp
d component\bluetooth\example\bt_a2dp_scatternet
d component\bluetooth\example\bt_app_audio_data
d component\bluetooth\example\bt_atcmd
fd component\bluetooth\example\bt_atcmd\atcmd_bt_fuzz_test.c
fd component\bluetooth\example\bt_atcmd\atcmd_bt_mesh_performence_test.c
fd component\bluetooth\example\bt_atcmd\atcmd_bt_pts.c
fd component\bluetooth\example\bt_atcmd\atcmd_bt_transfer_module.c
d component\bluetooth\example\bt_audio_mp_test
d component\bluetooth\example\bt_hfp
d component\bluetooth\example\bt_hid
d component\bluetooth\example\bt_rfc
d component\bluetooth\example\bt_spp
d component\bluetooth\rtk_stack\platform\amebalite
dd component\bluetooth\rtk_stack\src\mesh\inc\amebasmart
dd component\bluetooth\rtk_stack\src\mesh\inc\amebadplus
dd component\bluetooth\rtk_stack\src\mesh\inc\amebagreen2
dd component\bluetooth\rtk_stack\src\mesh\lib\amebasmart
dd component\bluetooth\rtk_stack\src\mesh\lib\amebadplus
dd component\bluetooth\rtk_stack\src\mesh\lib\amebagreen2
; tflite_micro
d component\tflite_micro
dd component\tflite_micro\examples
dd component\tflite_micro\tflm_unittest
dd component\tflite_micro\.git
fd component\tflite_micro\.clang-format
fd component\tflite_micro\sync\extract_tflm_unittest_srcs.sh
d component\tflite_micro\examples\build_utils
d component\tflite_micro\examples\tflm_hello_world
d component\tflite_micro\examples\tflm_micro_speech
d component\tflite_micro\examples\tflm_mnist
fd component\tflite_micro\examples\tflm_mnist\run_internal.sh
; aivoice
d component\aivoice
dd component\aivoice\examples
dd component\aivoice\.git
d component\aivoice\examples\build_utils
d component\aivoice\examples\full_flow_offline
d component\aivoice\examples\speechmind_demo
; peripheral
d example\peripheral
dd example\peripheral\mbed\ADC\mbed_adc_vbat_vol
dd example\peripheral\mbed\SDIO
dd example\peripheral\raw\ADC\raw_adc_tim_trig_vbat
dd example\peripheral\raw\CA32Trustzone
dd example\peripheral\raw\Display
dd example\peripheral\raw\I2C\i2c_dma_mode
dd example\peripheral\raw\IR
dd example\peripheral\raw\KSCAN
dd example\peripheral\raw\SDH
d example\network_protocol\captive_portal
d example\storage\vfs_sd_spi
d example\storage\vfs_sdcard
d example\storage\vfs_second_flash
d example\storage\vfs_usbh
f component\file_system\ftl\ftl.c
f component\file_system\ftl\ftl.h
f component\file_system\ftl\CMakeLists.txt
f component\file_system\littlefs\CMakeLists.txt
f component\file_system\littlefs\littlefs_adapter.c
f component\file_system\littlefs\littlefs_adapter.h
d component\file_system\littlefs\r2.50
d component\network\ssl_client
d component\os\freertos\freertos_v10.4.3
d component\osal
d component\log
; sdio
;d component\sdio\sd_host\inc
; wifi makefile
f component\wifi\simple_config\wifi_simple_config.c
f component\wifi\simple_config\wifi_simple_config.h
f component\wifi\simple_config\wifi_simple_config_parser.h
f component\wifi\driver\include\autoconf_8720e.h
f component\wifi\wifi_fw\amebalite\CMakeLists.txt
f component\wifi\wifi_fw\amebalite\km4.cmake
f component\wifi\wifi_fw\amebalite\kr4.cmake
fd tools\ameba\TraceTool\eFuseDefaultMap.json
d tools\iperf
f component\soc\amebalite\project\AmebaLite_Release_Note.txt
;
; file use f , dir use d
; "file copy and rename" use fr
; "file delete" use fd


; doc
dr component\soc\amebalite\project\release_tool\Doc \doc

; soc
d component\soc\amebalite

dd component\soc\amebalite\verification
dd component\soc\amebalite\rom
dd component\soc\amebalite\imgtool_floader

dd component\soc\amebalite\lib
f component\soc\amebalite\lib\bootloader\CMakeLists.txt
f component\soc\amebalite\lib\chipinfo\CMakeLists.txt
f component\soc\amebalite\lib\pmc\CMakeLists.txt

d component\soc\common\include
d component\soc\common\lzma
d component\soc\common\diagnose
d component\soc\common\cmsis-dsp
dd component\soc\common\cmsis-dsp\rom

d component\soc\usrcfg\amebalite
d component\soc\usrcfg\common

; project files
f component\soc\amebalite\project\CMakeLists.txt
f component\soc\amebalite\project\postbuild.cmake
f component\soc\amebalite\project\ameba_layout.ld
f component\soc\amebalite\project\manifest.json5
f component\soc\amebalite\project\Kconfig
f component\soc\amebalite\project\default.conf

; project km4
d component\soc\amebalite\project\project_km4

; asdk
dd component\soc\amebalite\project\project_km4\make_rom

fd component\soc\amebalite\project\project_km4\libs.cmake
fd component\soc\amebalite\project\project_km4\includeflags.cmake
fd component\soc\amebalite\project\project_km4\bluetooth_include.cmake

dd component\soc\amebalite\project\project_km4\lib
d component\soc\amebalite\project\project_km4\lib\application
d component\soc\amebalite\project\project_km4\lib\soc
dd component\soc\amebalite\project\project_km4\make_lib
dd component\soc\amebalite\project\project_km4\make_secure

fd component\soc\amebalite\project\project_km4\ld\ameba_rom.ld
fd component\soc\amebalite\project\project_km4\ld\ameba_rom_bin.ld
dd component\soc\amebalite\project\project_km4\ld_ns

dd component\soc\amebalite\project\project_km4\make
d component\soc\amebalite\project\project_km4\make\image1
d component\soc\amebalite\project\project_km4\make\image2
d component\soc\amebalite\project\project_km4\make\image3
d component\soc\amebalite\project\project_km4\make\image_floader
d component\soc\amebalite\project\project_km4\make\image_imgtool_floader


; project kr4
d component\soc\amebalite\project\project_kr4

; vsdk
dd component\soc\amebalite\project\project_kr4\make_rom

fd component\soc\amebalite\project\project_kr4\libs.cmake
fd component\soc\amebalite\project\project_kr4\includeflags.cmake
fd component\soc\amebalite\project\project_kr4\bluetooth_include.cmake

dd component\soc\amebalite\project\project_kr4\make_rom
dd component\soc\amebalite\project\project_kr4\lib
d component\soc\amebalite\project\project_kr4\lib\application
d component\soc\amebalite\project\project_kr4\lib\soc
dd component\soc\amebalite\project\project_kr4\make_lib

fd component\soc\amebalite\project\project_kr4\ld\ameba_rom.ld
fd component\soc\amebalite\project\project_kr4\ld\ameba_rom_bin.ld

dd component\soc\amebalite\project\project_kr4\make
d component\soc\amebalite\project\project_kr4\make\image2
