;cmake
d component\audio\libs\amebasmart
f component\audio\foundation\CMakeLists.txt
d component\audio\audio_hal\amebasmart
d component\audio\audio_hal\usb
d component\audio\interfaces\usb_audio
d component\audio\configs
d component\audio\third_party\speexdsp\include\
d component\audio\third_party\speexdsp\doc\
d component\audio\examples\audio_manager
d component\audio\examples\audio_a2dp
; aivoice
d component\aivoice
dd component\aivoice\examples
dd component\aivoice\.git
d component\aivoice\examples\build_utils
d component\aivoice\examples\full_flow_offline
d component\utils\ipc\ipc\
f component\utils\ipc\Kconfig
; ringbuffer
d component\utils\ringbuffer\
; crashdump
d component\soc\common\rtk_assert
d component\soc\common\crashdump\
dd component\soc\common\crashdump\arm
dd component\soc\common\crashdump\riscv
fd component\soc\common\crashdump\ameba_freertos_backtrace.c
fd component\soc\common\crashdump\include\ameba_rv32_backtrace.h
fd component\soc\common\crashdump\include\ameba_rv32_crashdump.h
d component\bluetooth\api
dd component\bluetooth\api\zephyr_stack
d component\bluetooth\bt_audio
fd component\bluetooth\bt_audio\audio_sync\bt_audio_sync.c
dd component\bluetooth\bt_audio\bt_codec\aac
d component\bluetooth\bt_audio\bt_codec\aac\libAACdec\include
d component\bluetooth\bt_audio\bt_codec\aac\libAACenc\include
dd component\bluetooth\bt_audio\bt_codec\lc3
d component\bluetooth\bt_audio\bt_codec\lc3\include
dd component\bluetooth\bt_audio\bt_codec\sbc
d component\bluetooth\bt_audio\bt_codec\sbc\common
d component\bluetooth\bt_audio\bt_codec\sbc\decoder\include
d component\bluetooth\bt_audio\bt_codec\sbc\encoder\include
d component\bluetooth\bt_audio\bt_codec\sbc\plc
fd component\bluetooth\bt_audio\bt_codec\sbc\plc\sbc_plc.c
dd component\bluetooth\bt_mp\bt_eqc
dd component\bluetooth\bt_mp\bt_fast_mp
dd component\bluetooth\driver\bt_inic
fd component\bluetooth\driver\hci\hci_if_inic.c
fd component\bluetooth\driver\hci\hci_if_inic.h
d component\bluetooth\driver\platform\amebasmart
d component\bluetooth\example\ble_audio
d component\bluetooth\example\ble_iso
d component\bluetooth\example\ble_mesh_ota\platform\amebasmart
d component\bluetooth\example\bt_a2dp
d component\bluetooth\example\bt_a2dp_hfp
d component\bluetooth\example\bt_a2dp_hfp_pbp
d component\bluetooth\example\bt_a2dp_scatternet
d component\bluetooth\example\bt_app_audio_data
d component\bluetooth\example\bt_atcmd
fd component\bluetooth\example\bt_atcmd\atcmd_bt_fuzz_test.c
fd component\bluetooth\example\bt_atcmd\atcmd_bt_mesh_performence_test.c
fd component\bluetooth\example\bt_atcmd\atcmd_bt_pts.c
fd component\bluetooth\example\bt_atcmd\atcmd_bt_transfer_module.c
d component\bluetooth\example\bt_audio_mp_test
d component\bluetooth\example\bt_hfp
d component\bluetooth\example\bt_hid
d component\bluetooth\example\bt_rfc
d component\bluetooth\example\bt_spp
d component\bluetooth\rtk_stack\platform\amebasmart
dd component\bluetooth\rtk_stack\src\mesh\inc\amebalite
dd component\bluetooth\rtk_stack\src\mesh\inc\amebadplus
dd component\bluetooth\rtk_stack\src\mesh\inc\amebagreen2
dd component\bluetooth\rtk_stack\src\mesh\lib\amebalite
dd component\bluetooth\rtk_stack\src\mesh\lib\amebadplus
dd component\bluetooth\rtk_stack\src\mesh\lib\amebagreen2
; tflite_micro
d component\tflite_micro
dd component\tflite_micro\examples
dd component\tflite_micro\tflm_unittest
dd component\tflite_micro\.git
fd component\tflite_micro\.clang-format
fd component\tflite_micro\sync\extract_tflm_unittest_srcs.sh
d component\tflite_micro\examples\build_utils
d component\tflite_micro\examples\tflm_hello_world
d component\tflite_micro\examples\tflm_micro_speech
d component\tflite_micro\examples\tflm_mnist
fd component\tflite_micro\examples\tflm_mnist\run_internal.sh
; dynamic app
d component\dynamic_app
; peripheral
d example\peripheral
dd example\peripheral\raw\Display\PPE
dd example\peripheral\raw\Display\QSPI
dd example\peripheral\mbed\SDIO
dd example\peripheral\raw\KSCAN
dd example\peripheral\raw\RDP
dd example\peripheral\raw\I2C\i2c_dma_mode
dd example\peripheral\raw\ECDSA
; application
; dd component\application
dd component\ui\LVGL\lvgl-8.3\lv_drivers\amebadplus
dd component\ui\LVGL\lvgl-8.3\lv_drivers\amebalite
dd component\ui\LVGL\lvgl-8.3\lv_drivers\amebagreen2
dd component\ui\LVGL\lvgl-8.3\port\amebadplus
dd component\ui\LVGL\lvgl-8.3\port\amebalite
dd component\ui\LVGL\lvgl-8.3\port\amebagreen2
dd component\ui\LVGL\lvgl-9.3\lv_drivers\amebadplus
dd component\ui\LVGL\lvgl-9.3\lv_drivers\amebalite
dd component\ui\LVGL\lvgl-9.3\lv_drivers\amebagreen2
dd component\ui\LVGL\lvgl-9.3\port\amebasdplus
dd component\ui\LVGL\lvgl-9.3\port\amebadlite
dd component\ui\LVGL\lvgl-9.3\port\amebagreen2
d example\storage\vfs_sd_spi
d example\storage\vfs_sdcard
d example\storage\vfs_second_flash
d example\storage\vfs_usbh
; usb
d example\usb
dd example\usb\usbd_inic
dd example\usb\usbd_inic_dplus
d component\file_system\ftl
d component\file_system\littlefs
d component\os\freertos\freertos_v10.5.1
d component\os\freertos\freertos_v10.2.1_smp
d component\osal
d component\log
; usb class
d component\usb
dd component\usb\verification
d component\usb\common
fd component\usb\common\usb_hal.c
fd component\usb\common\usb_os.c
fd component\usb\common\usb_phy.c
fd component\usb\common\usb_ringbuf.c
fd component\usb\common\usb_hal.h
fd component\usb\common\usb_regs.h
dd component\usb\device\core
f component\usb\device\core\usbd.h
dd component\usb\device\inic
dd component\usb\device\inic_dplus
dd component\usb\device\verify
dd component\usb\host\core
f component\usb\host\core\usbh.h
dd component\usb\host\verify
; wifi CMakeLists
d component\wifi\whc\whc_host_linux
dd component\wifi\whc\whc_host_linux\bridge
dd component\wifi\whc\whc_host_linux\common
d component\wifi\whc\whc_host_linux\common\netdev
d component\wifi\whc\whc_host_linux\fullmac
dd component\wifi\whc\whc_host_linux\fullmac\sdio
dd component\wifi\whc\whc_host_linux\fullmac\spi
dd component\wifi\whc\whc_host_linux\fullmac\usb
;wifi cast
f component\wifi\rtk_app\wifi_cast\wifi_intf_drv_to_app_cast.h
;f component\wifi\simple_config\wifi_simple_config.c
;f component\wifi\simple_config\wifi_simple_config.h
;f component\wifi\simple_config\wifi_simple_config_parser.h
f component\wifi\driver\include\autoconf_8730e.h
f component\wifi\wifi_fw\amebasmart\CMakeLists.txt
f tools\iperf.exe
f component\soc\amebasmart\project\AmebaSmart_Release_Note.txt
;
; file use f , dir use d
; "file copy and rename" use fr
; "file delete" use fd

; doc
dr amebasmart_gcc_project\utils\release_tool\Doc \doc

; soc
d component\soc\amebasmart
d component\soc\amebasmart\main
dd component\soc\amebasmart\atf\plat\realtek\sheipa\lib
dd component\soc\amebasmart\rom
dd component\soc\amebasmart\verification
dd component\soc\amebasmart\imgtool_floader
dd component\soc\amebasmart\lib
f component\soc\amebasmart\lib\bootloader\CMakeLists.txt
f component\soc\amebasmart\lib\chipinfo\CMakeLists.txt
f component\soc\amebasmart\lib\pmc\CMakeLists.txt
d component\soc\common\include
d component\soc\common\lzma
d component\soc\common\diagnose
d component\soc\common\cmsis-dsp
dd component\soc\common\cmsis-dsp\rom
d component\soc\usrcfg\amebasmart
d component\soc\usrcfg\common
; project files
f component\soc\amebasmart\project\CMakeLists.txt
f component\soc\amebasmart\project\platform_project_config.cmake
f component\soc\amebasmart\project\ameba_layout.ld
f component\soc\amebasmart\project\manifest.json5
f component\soc\amebasmart\project\Kconfig
f component\soc\amebasmart\project\default.conf
f component\soc\amebasmart\project\postbuild.cmake
; ap
d component\soc\amebasmart\project\project_ap
; ap asdk
dd component\soc\amebasmart\project\project_ap\lib
d component\soc\amebasmart\project\project_ap\lib\application
d component\soc\amebasmart\project\project_ap\lib\soc
fd component\soc\amebasmart\project\project_ap\lib\soc\lib_Vmin_Test.a
dd component\soc\amebasmart\project\project_ap\make
d component\soc\amebasmart\project\project_ap\make\atf
d component\soc\amebasmart\project\project_ap\make\image2
d component\soc\amebasmart\project\project_ap\make\image3

; hp
d component\soc\amebasmart\project\project_hp

; hp asdk
dd component\soc\amebasmart\project\project_hp\make_rom

dd component\soc\amebasmart\project\project_hp\lib
d component\soc\amebasmart\project\project_hp\lib\application
d component\soc\amebasmart\project\project_hp\lib\soc
fd component\soc\amebasmart\project\project_hp\Makefile.rom
dd component\soc\amebasmart\project\project_hp\make_lib
fd component\soc\amebasmart\project\project_hp\ld\ameba_rom.ld
fd component\soc\amebasmart\project\project_hp\ld\ameba_rom_bin.ld
dd component\soc\amebasmart\project\project_hp\ld_ns
dd component\soc\amebasmart\project\project_hp\make\rtk_coex
#dd component\soc\amebasmart\project\project_hp\flashloader
dd component\soc\amebasmart\project\project_hp\make
d component\soc\amebasmart\project\project_hp\make\image1
d component\soc\amebasmart\project\project_hp\make\image2
d component\soc\amebasmart\project\project_hp\make\image_floader
d component\soc\amebasmart\project\project_hp\make\image_imgtool_floader
; lp
f component\soc\amebasmart\project\project_lp\CMakeLists.txt
f component\soc\amebasmart\project\project_lp\Kconfig
; lp asdk
d component\soc\amebasmart\project\project_lp\config
d component\soc\amebasmart\project\project_lp\ld
dd component\soc\amebasmart\project\project_lp\lib
d component\soc\amebasmart\project\project_lp\lib\application
d component\soc\amebasmart\project\project_lp\lib\soc
d component\soc\amebasmart\project\project_lp\make\image2
dd component\soc\amebasmart\project\project_lp\make_lib
f component\soc\amebasmart\project\project_lp\CMakeLists.txt
fd component\soc\amebasmart\project\project_lp\Makefile.include.gen
fd component\soc\amebasmart\project\project_lp\Makefile.rom
fd component\soc\amebasmart\project\project_lp\ld\ameba_rom.ld
fd component\soc\amebasmart\project\project_lp\ld\ameba_rom_bin.ld

; release note
;fr release_note.txt release_note_amebaSmart.txt
