# This file is generated automatically by : python menuconfig.py -s utils/confs_release_tool/rls_usb_wpaoh.conf
CONFIG_USB_OTG_EN_MENU=y
CONFIG_USBD_INIC_MENU=y
CONFIG_WHC_DEV_MENU=y
CONFIG_WHC_INTF_USB=y
