# This file is generated automatically by : python menuconfig.py -s ../tools/scripts/release_tool/amebadplus/confs_release_tool/rls_usb_wpaod_tcpip.conf
CONFIG_USB_OTG_EN_MENU=y
CONFIG_USBD_INIC_MENU=y
CONFIG_WHC_DEV_MENU=y
CONFIG_WHC_INTF_USB=y
CONFIG_WHC_WIFI_API_PATH=n
CONFIG_WHC_WPA_SUPPLICANT_OFFLOAD_FOR_KM4=y
CONFIG_WHC_DEV_TCPIP_KEEPALIVE_FOR_KM4=y
